name: CI
on:
  push:
    branches:
      - main
      - renovate-github/**
  pull_request:
    branches:
      - main

jobs:
  npm:
    name: NPM
    runs-on: ubuntu-latest
    env:
      NX_RUN_GROUP: ${{ github.run_id }}
      NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.1.0

      - name: Setup Node.js
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16.x

      - name: NPM
        uses: ng-easy/npm-setup@v2.0.14

  build:
    name: Build
    needs: [npm]
    runs-on: ubuntu-latest
    env:
      NX_RUN_GROUP: ${{ github.run_id }}
      NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0 # Fetch all branches and commits so that Nx affected has a base to compare against

      - name: Setup Node.js
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16.x

      - name: NPM
        uses: ng-easy/npm-setup@v2.0.14
        with:
          nx-key: build

      - name: Nx Set SHAs
        uses: nrwl/nx-set-shas@v3.0.0

      - name: Build
        uses: mansagroup/nrwl-nx-action@v3.1.0
        with:
          targets: build
          affected: 'true'
          parallel: 3
          nxCloud: 'true'

  lint:
    name: Lint
    needs: [npm]
    runs-on: ubuntu-latest
    env:
      NX_RUN_GROUP: ${{ github.run_id }}
      NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0 # Fetch all branches and commits so that Nx affected has a base to compare against

      - name: Setup Node.js
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16.x

      - name: NPM
        uses: ng-easy/npm-setup@v2.0.14
        with:
          nx-key: lint

      - name: Nx Set SHAs
        uses: nrwl/nx-set-shas@v3.0.0

      - name: Lint
        uses: mansagroup/nrwl-nx-action@v3.1.0
        with:
          targets: lint
          affected: 'true'
          parallel: 3
          nxCloud: 'true'

      - name: lint workspace
        run: npm run lint:workspace

  test:
    name: Test
    needs: [npm]
    runs-on: ubuntu-latest
    env:
      NX_RUN_GROUP: ${{ github.run_id }}
      NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0 # Fetch all branches and commits so that Nx affected has a base to compare against

      - name: Setup Node.js
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16.x

      - name: NPM
        uses: ng-easy/npm-setup@v2.0.14
        with:
          nx-key: test

      - name: Nx Set SHAs
        uses: nrwl/nx-set-shas@v3.0.0

      - name: Test
        uses: mansagroup/nrwl-nx-action@v3.1.0
        with:
          targets: test
          affected: 'true'
          parallel: 3
          nxCloud: 'true'

      - name: Codecov
        uses: codecov/codecov-action@v3
        if: hashFiles('coverage/**/*') != ''
        with:
          fail_ci_if_error: true
          verbose: true

  e2e:
    name: e2e
    needs: [npm]
    runs-on: ubuntu-latest
    env:
      NX_RUN_GROUP: ${{ github.run_id }}
      NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0 # Fetch all branches and commits so that Nx affected has a base to compare against

      - name: Setup Node.js
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16.x

      - name: NPM
        uses: ng-easy/npm-setup@v2.0.14
        with:
          nx-key: e2e

      - name: Nx Set SHAs
        uses: nrwl/nx-set-shas@v3.0.0

      - name: e2e
        uses: mansagroup/nrwl-nx-action@v3.1.0
        with:
          targets: e2e
          affected: 'true'
          parallel: 1
          nxCloud: 'true'
