name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - renovate-github/**
  pull_request:
    branches:
      - main

jobs:
  npm:
    name: NPM
    runs-on: ubuntu-latest
    env:
      NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.7

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.x

      - name: NPM
        uses: ng-easy/npm-setup@v4.0.0

  build:
    name: Build
    needs: [npm]
    runs-on: ubuntu-latest
    env:
      NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0 # Fetch all branches and commits so that Nx affected has a base to compare against

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.x

      - name: NPM
        uses: ng-easy/npm-setup@v4.0.0
        with:
          nx-key: build

      - name: Nx Set SHAs
        uses: nrwl/nx-set-shas@v4.0.6

      - name: Build
        run: npx nx affected --target=build --parallel=3

  lint:
    name: Lint
    needs: [npm]
    runs-on: ubuntu-latest
    env:
      NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0 # Fetch all branches and commits so that Nx affected has a base to compare against

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.x

      - name: NPM
        uses: ng-easy/npm-setup@v4.0.0
        with:
          nx-key: lint

      - name: Nx Set SHAs
        uses: nrwl/nx-set-shas@v4.0.6

      - name: Lint
        run: npx nx affected --target=lint --parallel=3

  test:
    name: Test
    needs: [npm]
    runs-on: ubuntu-latest
    env:
      NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0 # Fetch all branches and commits so that Nx affected has a base to compare against

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.x

      - name: NPM
        uses: ng-easy/npm-setup@v4.0.0
        with:
          nx-key: test

      - name: Nx Set SHAs
        uses: nrwl/nx-set-shas@v4.0.6

      - name: Test
        run: npx nx affected --target=test --parallel=3

      - name: Codecov
        uses: codecov/codecov-action@v4
        if: hashFiles('coverage/**/*') != ''
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true

  e2e:
    name: e2e
    needs: [npm]
    runs-on: ubuntu-latest
    env:
      NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0 # Fetch all branches and commits so that Nx affected has a base to compare against

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.x

      - name: NPM
        uses: ng-easy/npm-setup@v4.0.0
        with:
          nx-key: e2e

      - name: Nx Set SHAs
        uses: nrwl/nx-set-shas@v4.0.6

      - name: e2e
        run: npx nx affected --target=e2e --parallel=1

  docs:
    name: Docs
    needs: [npm]
    runs-on: ubuntu-latest
    env:
      NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0 # Fetch all branches and commits so that Nx affected has a base to compare against

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.x

      - name: NPM
        uses: ng-easy/npm-setup@v4.0.0
        with:
          nx-key: docs

      - name: Nx Set SHAs
        uses: nrwl/nx-set-shas@v4.0.6

      - name: Docs Coverage
        run: npx nx affected --target=docs --configuration=coverage --parallel=3
