name: Next
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # daily at 00:00

jobs:
  next:
    name: Pipeline with @next version
    runs-on: ubuntu-latest
    env:
      NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.1

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.x

      - name: NPM
        uses: ng-easy/npm-setup@v4.0.0
        with:
          nx-key: next

      - name: Migrate @next
        run: |
          npx --no-install nx migrate next
          npx --no-install nx migrate @angular/core@next
          npx --no-install nx migrate @angular/cli@next
          npx --no-install nx migrate @schematics/angular@next
          npx --no-install nx migrate @angular-eslint/eslint-plugin@next
          npx --no-install nx migrate @angular-eslint/eslint-plugin-template@next
          npx --no-install nx migrate @angular-eslint/template-parser@next
          npx --no-install nx migrate @ngrx/signals@next
          rm -rf node_modules
          rm package-lock.json
          npm install --force
          npx --no-install nx migrate --run-migrations --if-exists
          npm install --force
          rm -f migrations.json

      - name: Lint
        run: npx --no-install nx run-many --target=lint --fix --parallel=3

      - name: Build
        run: npx --no-install nx run-many --target=build --parallel=3

      - name: Test
        run: npx --no-install nx run-many --target=test --parallel=3

      - name: e2e
        run: npx --no-install nx run-many --target=e2e --parallel=1
