name: Next
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # daily at 00:00

jobs:
  next:
    name: Pipeline with @next version
    runs-on: ubuntu-latest
    env:
      NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.4.0

      - name: Setup Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18.x

      - name: NPM
        uses: ng-easy/npm-setup@v3.0.0
        with:
          nx-key: next

      - name: Migrate @next
        run: |
          echo '{"migrations":[]}' > migrations.json
          npx --no-install nx migrate next
          npm install --force --ignore-scripts
          npx --no-install nx migrate --run-migrations

      - name: Lint
        run: npx --no-install nx run-many --target=lint --parallel=3

      - name: Lint workspace
        run: npm run lint:workspace

      - name: Build
        run: npx --no-install nx run-many --target=build --parallel=3

      - name: Test
        run: npx --no-install nx run-many --target=test --parallel=3

      - name: e2e
        run: npx --no-install nx run-many --target=e2e --parallel=3
