name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: '0/15 * * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v32.90.0
        env:
          NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}
          LOG_LEVEL: debug
        with:
          configurationFile: renovate.config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
