name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.1

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@8f6b0f762415909f60b0efb1817c4dee029ea806 # v40.1.1
        env:
          LOG_LEVEL: debug
          NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}
        with:
          configurationFile: .github/renovate-config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
